---
title: "`r params$my_valentine`"
subtitle: "Yours truly, `r params$sent_from$given`"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
knit: source("_render_from.R")$value
params:
  my_valentine: "Nothing matters"
  from_group: NULL
  send_to:
    value:
      given: "Annetha"
      family: "Mills"
  sent_from:
    value:
      given: "Mary"
      family: "Berry"
---

```{r include=FALSE}
library(tidyverse)
library(bakeoff)
library(epoxy)
send_to <- baker_results %>% 
  filter(baker_first == params$send_to$given & baker_last == params$send_to$family)
index_baker <- send_to$baker
your_bakes <- challenge_results %>% 
  filter(baker == index_baker) %>% 
  drop_na(showstopper)
```

### To: 

```{glue data=params$send_to}
{given} {family}
```

### From:

```{glue data=params$sent_from}
{given} {family}
```

```{r include=FALSE}
is_from_group <- ifelse(is.null(params$from_group), FALSE, TRUE)
```

```{r eval=is_from_group, echo=FALSE}
group <- purrr::flatten_dfr(params$from_group)
```




---

```{glue data=send_to}
{baker}, {baker}, you baked your heart out.

You were star baker {star_baker} times.

We met you on {first_date_appeared}.

After {total_episodes_appeared} episodes, we said our goodbyes.
```

Your showstoppers really blew us away:

```{glue data=your_bakes}
- {showstopper}
```

And your signature bakes- we want one every Sunday!

```{glue data=your_bakes}
- {signature}
```

You brought us great joy, we'll miss you, it's true.

Please keep on baking- without your bakes we'd be blue!

---

```{r comment="#"}
rmarkdown::metadata
```

\
\
\


See: https://www.tjmahr.com/lists-knitr-secret-weapon/

```{r}
knitted <- list(
  when = format(Sys.Date()),
  where = knitr::current_input(),
  with = packageVersion("knitr"),
  doc_url = downlit::autolink_url("rmarkdown::render()")
)
```

```{glue data=knitted}
Report prepared on {when} from `{where}` with knitr version {with} {emo::ji("happy")}. Read more about [`rmarkdown::render()`]({doc_url}).
```
